apiVersion: v2
name: block-producer
description: A Helm chart for Mina Protocol's block producing network nodes
type: application
version: 0.3.2
appVersion: 1.16.0
dependencies:
  - name: common-utilities
    version: 0.0.4
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://github.com/MinaProtocol/mina/blob/develop/frontend/website/public/static/img/coda-logo@3x.png
keywords:
- block-producer
- stake
- delegate
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/src/lib/block_producer

